version: "3.7"

services:

  nginx:
    image: nginx:alpine
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./docker/nginx/sites:/etc/nginx/conf.d
      - ./docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
    networks:
      - usersNetwork
    environment:
      - APP_ENV=${APP_ENV}

  php:
    build: docker/php
    volumes:
      - .:/var/www/html
    networks:
      - usersNetwork

  mysql:
    image: mysql:5.7
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - usersMysqldata:/var/lib/mysql
    networks:
      - usersNetwork
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  redis:
    image: redis:alpine
    volumes:
      - usersRedisdata:/data
    networks:
      - usersNetwork

networks:
  usersNetwork:
    driver: "bridge"

volumes:
  usersMysqldata:
    driver: "local"
  usersRedisdata:
    driver: "local"
