version: "3.7"

services:

  nginx:
    image: nginx:alpine
    container_name: usersWebserver
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./docker/nginx/sites:/etc/nginx/conf.d
      - ./docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
    networks:
      - usersNetwork
    environment:
      - APP_ENV=${APP_ENV}

  php:
    build: docker/php
    container_name: usersPhp
    ports:
      - "${SUPERVISOR_PORT}:9001" # http://127.0.0.1:9001 - supervisor web
    volumes:
      - .:/var/www/html
      - ./supervisor/supervisord.conf:/etc/supervisord.conf
    networks:
      - usersNetwork

  mysql:
    image: mysql:5.7
    container_name: usersDb
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - usersDbdata:/var/lib/mysql
    networks:
      - usersNetwork
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  redis:
    image: redis:alpine
    container_name: usersRedis
    volumes:
      - usersRedisdata:/data
    networks:
      - usersNetwork

networks:
  usersNetwork:
    driver: "bridge"

volumes:
  usersDbdata:
    driver: "local"
  usersRedisdata:
    driver: "local"
